version: "2.4"

services:
  odoo:
    image: docker.io/ibees/dod14:14.0
    build:
      context: ./odoo
      labels:
        app_name: "dod14"
      args:
        ODOO_VERSION: "14.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
      EMAIL_FROM: ""
      PGDATABASE: &dbname 111
      PGUSER: &dbuser "odoo"
      DB_FILTER: ".*"
      PROXY_MODE: "true"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z

volumes:
  filestore:

networks:
  default:
    # driver_opts:
    #   encrypted: 1

  # db:
  #   image: ghcr.io/tecnativa/postgres-autoconf:13-alpine
  #   shm_size: 512mb
  #   environment:
  #     POSTGRES_DB: *dbname
  #     POSTGRES_USER: *dbuser
  #     CONF_EXTRA: |
  #       work_mem = 512MB
  #   volumes:
  #     - db:/var/lib/postgresql/data:z

  # smtpfake:
  #   image: mailhog/mailhog
