version: "2.4"

services:
  odoo:
    image: docker.io/ibees/dod14:14.0
    build:
      context: ./odoo
      labels:
        app_name: "dod14"
      args:
        ODOO_VERSION: "14.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"

networks:
  default:
    internal: true
