apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odoo
  name: odoo
  namespace: odoo14
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - image: docker.io/ibees/dod14:14.0
          name: web
          env:
            - name: PGHOST
              value: knotty-whip-postgresql-ha-pgpool.default.svc.cluster.local
            - name: PGPASSWORD
              value: S64O8olMJZ
            - name: PGUSER
              value: odoo
            - name: DB_FILTER
              value: ".*"
            - name: PROXY_MODE
              value: "true"
            - name: ADMIN_PASSWORD
              value: "111"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8069
          resources:
            limits:
              memory: 2048Mi
              cpu: 500m
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 300
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 6
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 6
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo-data
      restartPolicy: Always
      # nodeSelector:
      #   node_name: node-A
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-data-claim
