apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: odoo
  name: odoo-data-claim
  namespace: odoo14
  # annotations:
  #   appuio.ch/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
