apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dod14
  namespace: argocd
spec:
  project: dod14
  source:
    repoURL: https://github.com/marcel-dempers/docker-development-youtube-series.git
    targetRevision: HEAD
    path: argo/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dod14
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
